# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.13.0.post23+g6157d47fd.d20230327 on Thu Apr 27 10:58:19 2023
# Model: Sediment Delivery Ratio

import logging
import os
import sys

import natcap.invest.sdr.sdr
import natcap.invest.utils
from natcap.invest import datastack

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])

stack = datastack.extract_parameter_set('./SDR/sdr_gura.invs.json')
args = stack.args
args['workspace_dir'] = os.path.join(
    os.environ['SCRATCH'], 'sdr-workspace')

if __name__ == '__main__':
    natcap.invest.sdr.sdr.execute(args)
