# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.13.0.post23+g6157d47fd.d20230327 on Thu Apr 27 10:58:19 2023
# Model: Sediment Delivery Ratio

import logging
import sys

import natcap.invest.sdr.sdr
import natcap.invest.utils

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])

args = {
    'biophysical_table_path': '',
    'dem_path': '',
    'drainage_path': '',
    'erodibility_path': '',
    'erosivity_path': '',
    'ic_0_param': '',
    'k_param': '',
    'l_max': '',
    'lulc_path': '',
    'n_workers': '',
    'results_suffix': '',
    'sdr_max': '',
    'threshold_flow_accumulation': '',
    'watersheds_path': '',
    'workspace_dir': '',
}

if __name__ == '__main__':
    natcap.invest.sdr.sdr.execute(args)
